### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by iamrishav** [MayankGupta73/MedLoco-Hospital-Locator#2]
![error](https://user-images.githubusercontent.com/42150367/54317302-c3ca2b80-4608-11e9-8042-8415895d9da2.png)
<b>error when getting nearby hospitals</b> @MayankGupta73

**Comment by MayankGupta73** [comment]
Thanks for pointing out that bug.
It was occurring due to there being less hospitals in a 3km radius of some areas.

I fixed the problem and also increased the search radius to 5km so hopefully this problem should not occur now.

**Comment by iamrishav** [comment]
![error](https://user-images.githubusercontent.com/42150367/54337656-8b047380-4655-11e9-8eeb-9041b234100d.png)
there is again anothe indexoutofboundexception @MayankGupta73

**Comment by MayankGupta73** [comment]
It seems that there is no hospital near the area where you are testing the app from which should not normally occur.
I have made some changes and it shouldn't give this error after the latest commit.

Please check and see if there is any error now.

**Comment by iamrishav** [comment]
hello sir,
 there is many hospital near me

**Comment by iamrishav** [comment]
can you tell me what i will do to run your app
 i replaced your google maps key with my key
is there anything else i want to change

**Comment by MayankGupta73** [comment]
You just need to replace my key with yours.
For release in app/src/release/res/values/google_maps_api.xml
For debug in app\src\debug\res\values\google_maps_api.xml

Also do the changes I mentioned in the reply to the pull request (making a keys.xml file).
That should do it.

**Comment by iamrishav** [comment]
![erroe](https://user-images.githubusercontent.com/42150367/54344509-06baec00-4667-11e9-86e9-d1d3e225fa4f.png)
can you tell me what is the error, also i enabled the maps sdk for android and places sdk

**Comment by MayankGupta73** [comment]
Could you paste the portion of the stack trace where the app is crashing because I can't find any error in this.

Also enable the Distance Matrix API as well.

**Comment by iamrishav** [comment]
hello sir
can you run my app to your computer and debug the error, please 
also i added my api key and also enable the distance matrix api
https://github.com/iamrishav/LifeLine
@MayankGupta73

**Comment by MayankGupta73** [comment]
I'm sorry but I won't be able to do this now.
But if you have any specific error I would be happy to point you in the right direction.

**Comment by iamrishav** [comment]
it is not showing any hospital but there is many hospitals near me

**Comment by MayankGupta73** [comment]
The app fetches data from the Google places Api.
Maybe the hospitals in your area are not showing up in the google places search for some reason.
Maybe you can try searching for a specific hospital using the search bar at the top of the app.

**Comment by iamrishav** [comment]
search bar is also not working
it is showing no result found in 5km radius means it is not getting any response , if possible please fing the bug in my repo
<b>it is showing my current location properly</b> 
https://github.com/iamrishav/LifeLine
@MayankGupta73

**Comment by MayankGupta73** [comment]
To check whether the maps is detecting hospitals in your area you can try my app. The play store link is in the github repo. 
Otherwise I'm not sure what is going wrong.

**Comment by iamrishav** [comment]
your playstore app  is working well

**Comment by MayankGupta73** [comment]
I see.
Then I'm not sure what the problem is.
I would recommend you manually check whether the API response is correct by using log statements.
Then you can go forward from there.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by iamrishav** [comment]
![error2](https://user-images.githubusercontent.com/42150367/54461587-028bed00-4793-11e9-9e80-86052527a34d.png)

please check log TAG as "onResponse: Response Received "
Is it getting right response when calling method response.body()

**Comment by MayankGupta73** [comment]
At least the object type looks correct.
You should check the contents and properly debug the app to see what's going wrong.

**Comment by veronicaAoko** [comment]
hi,i know this issue is closed but am having the same problem....the app is running successfully but says no result found in a 5km radius.am at a place where there is plenty of hospitals
![screen1](https://user-images.githubusercontent.com/57744481/75092419-63699b00-5588-11ea-8511-c4e8004daa58.PNG)
Thats the errror on my logs.help....thanks in advance

**Comment by MayankGupta73** [comment]
Is there any other error in the logs? The one you have posted does not seem to be related to your issue and should not affect the running of the app.

Have you added your google maps key in the required locations as discussed above? Mostly the error of hospitals not being shown is due to some error with the Google APIs. 
I would recommend checking whether your key is correct and if you have enabled the maps API, distance matrix API and places API in your google cloud console.

**Comment by veronicaAoko** [comment]
i have enabled all the APIs that you have mentioned. There is also this in the log
![screen2](https://user-images.githubusercontent.com/57744481/75093438-c6f8c600-5592-11ea-875b-c9fe1aa5c32b.PNG)

**Comment by MayankGupta73** [comment]
This error also does not seem to be the cause of your problem. If this is the only error in your logs then I can't think of any reason for the problem to occur.
On my side, I verified that the app is running without problems on my phone. The only thing I can think of which may be causing issues for you is that your key is somehow not working.

I would recommend that you verify if both the debug google_maps_api.xml and release google_maps_api.xml are correct. If your debug app continues giving issues maybe you can try building a release version of the apk and checking if the problem persists. Other than that I cannot think of any solution.
